"use client";

import type { Metadata } from "next";
import { Authenticator } from '@aws-amplify/ui-react';

import { Inter } from 'next/font/google';

import '@aws-amplify/ui-react/styles.css';
import './app.css';

const inter = Inter({ subsets: ["latin"] });

// TODO: Add metadata - Not allowed client 'use client'
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Authenticator>{children}</Authenticator>
      </body>
    </html>
  );
}
